# Executive Summary

<!--
This section provides a condensed view of the entire proposal, one page long.
It should be a comprehensive high-level overview that captures the essence of the proposal, including its goals, methods, expected outcomes, deliverables, and budget.

TODO: add budget overview
-->

This work proposes exploration of a more complete implementation of the
debug-adapter protocol [@dap-spec] (DAP) protocol, which we anticipate will
require changes to R internals. We plan to prepare a patch to R to expand
the capabilities of `options(browser.hook)` (enabled using feature flag
`USE_BROWSER_HOOK`) to expose hooks at appropriate points that would permit
a more comprehensive and direct implementation of the DAP.

The debug-adapter protocol is a widely supported standard, which specifies how
an interactive development environment (IDE) can interact with a background
process to manage language-specific debugging features. Hallmark features
include breakpoint management, stepping through code, and viewing variables
local to the scope being debugged. In R we have the luxury of debugging tools
that are built-in to the core language, exposing all of these features at the
command-line. However, this interface can be alienating to beginners, where the
more visual interaction through an IDE can make these tools more accessible.

While there are existing projects that implement the debug-adapter protocol,
namely `vscDebugger` [@vscDebugger] and `ark` [@ark], both are limited in their
scope and bring both additional software requirements. Neither is capable of
providing a debugging experience in a way that is fully decoupled from the IDE.

This work has been in slow development for some years. Author Doug Kelkhoff
has produced a concept package [@debugadapter] which proved the potential of 
the project. While a few challenges were identified early on, the major
bottlenecks have been resolved in recent versions of R. Specifically, the
introduction of the development flag `USE_BROWSER_HOOK` allows effective
interaction with the state of the debugger such that we can manage the debug
state natively in R, without a parent process intercepting output and without
requiring a new standard for surfacing a console. However, even though this hook
may make a proper debug interface possible, it is by no means convenient or
stable. With only this hook, a implementation leveraging this hook is left to
make many assumptions about the state of the debugger in order to present
a intuitive browser-like prompt. Pursuing this work effectively requires
dedicated time, closer communication with the R Core to use and provide feedback
on development features, and to thoroughly test the solution against a wide
set of IDEs. To bring this project to fruition, I've partnered with Pachá.
Together, we're pursuing funding to support Pachá while working on this project.

As a result of this work we plan to (1) implement a proof-of-concept DAP
server that can be run as a part of an interactive R session, (2) propose
changes to R's internals that would improve the ease and reliability of a DAP
implementation (3) raise awareness within the R Core for the importance of
having an R-native solution for this problem as a central part of any modern
language ecosystem, and (4) provide feedback to the R Core team regarding the
in-development tools for interfacing with the debug state.
